const imageGalleryData = [
	{
		src:"assets/img/gallery/archi.jpg"
	},
	{
		src:"assets/img/gallery/gallery-1.jpg"
	},
	{
		src:"assets/img/gallery/gallery-10.jpg"
	},
	{
		src:"assets/img/gallery/gallery-11.jpg"
	},
	{
		src:"assets/img/gallery/gallery-12.jpg"
	},
	{
		src:"assets/img/gallery/gallery-13.jpg"
	},
	{
		src:"assets/img/gallery/gallery-14.jpg"
	},
	{
		src:"assets/img/gallery/gallery-15.jpg"
	},
	{
		src:"assets/img/gallery/gallery-16.jpg"
	},
	{
		src:"assets/img/gallery/gallery-2.jpg"
	},
	{
		src:"assets/img/gallery/gallery-3.jpg"
	},
	{
		src:"assets/img/gallery/gallery-4.jpg"
	},
	{
		src:"assets/img/gallery/gallery-5.jpg"
	},
	{
		src:"assets/img/gallery/gallery-6.jpg"
	},
	{
		src:"assets/img/gallery/gallery-7.jpg"
	},
	{
		src:"assets/img/gallery/gallery-8.jpg"
	},
	{
		src:"assets/img/gallery/gallery-9.jpg"
	}
];